---
# MetalLB Handlers

- name: restart metallb controller
  kubernetes.core.k8s:
    state: present
    api_version: apps/v1
    kind: Deployment
    name: controller
    namespace: "{{ metallb_namespace }}"
    definition:
      spec:
        template:
          metadata:
            annotations:
              ansible.restart: "{{ ansible_date_time.epoch }}"
  listen: "restart metallb"

- name: restart metallb speaker
  kubernetes.core.k8s:
    state: present
    api_version: apps/v1
    kind: DaemonSet
    name: speaker
    namespace: "{{ metallb_namespace }}"
    definition:
      spec:
        template:
          metadata:
            annotations:
              ansible.restart: "{{ ansible_date_time.epoch }}"
  listen: "restart metallb"

- name: wait for metallb ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ metallb_namespace }}"
    label_selectors:
      - "app=metallb"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
  listen: "wait for metallb"