---
# Temporary RBAC fix to allow Argo Workflows controller to access secrets in iris-demo namespace
# TODO: Replace with centralized secret management (Vault/ESO) for production

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argowf-cross-namespace-secrets
  annotations:
    description: "Temporary fix for cross-namespace secret access - replace with Vault/ESO"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  # TODO: Add resourceNames restriction after verifying basic access works
  # resourceNames: ["ghcr", "ml-platform"]  # Only allow these specific secrets

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argowf-cross-namespace-secrets
  annotations:
    description: "Temporary binding for Argo Workflows cross-namespace secret access"
subjects:
- kind: ServiceAccount
  name: argo-workflows-workflow-controller
  namespace: argowf
roleRef:
  kind: ClusterRole
  name: argowf-cross-namespace-secrets
  apiGroup: rbac.authorization.k8s.io