---
# JupyterHub Configuration
jupyterhub_namespace: jupyterhub
jupyterhub_name: jupyterhub
jupyterhub_chart_ref: jupyterhub/jupyterhub

# Service Configuration
jupyterhub_nodeport: 30888
jupyterhub_service_type: NodePort

# Authentication Configuration
jupyterhub_auth_type: dummy
jupyterhub_password: mlops123

# User Environment Configuration
# Default to Harbor registry for custom images
jupyterhub_image_name: "{{ harbor_standalone_registry | default('192.168.1.100') }}/library/financial-predictor-jupyter"
jupyterhub_image_tag: latest
jupyterhub_default_url: /lab

# Storage Configuration
jupyterhub_storage_type: none  # Use 'dynamic' for persistent storage
jupyterhub_storage_class: nfs-shared
jupyterhub_storage_size: 10Gi

# Resource Configuration (Increased for generous allocation given your cluster capacity)
# Hub resources - Increased slightly for robustness
jupyterhub_hub_memory_request: 1Gi   # Was 512Mi
jupyterhub_hub_memory_limit: 2Gi   # Was 1Gi
jupyterhub_hub_cpu_request: 0.5    # 500m - Was 0.2
jupyterhub_hub_cpu_limit: 1.0      # 1000m - Was 0.5

# User resources - Significantly increased for MLOps workloads
jupyterhub_user_memory_request: 8Gi  # Was 1Gi
jupyterhub_user_memory_limit: 16Gi # Was 2Gi
jupyterhub_user_cpu_request: 2.0     # 2000m - Was 0.1
jupyterhub_user_cpu_limit: 4.0       # 4000m - Was 1.0

# Helm Configuration
helm_wait_timeout: 600s
helm_retries: 3
helm_retry_delay: 30