---
# MetalLB Default Configuration

# MetalLB Version
metallb_version: "v0.14.8"

# MetalLB Namespace
metallb_namespace: "metallb-system"

# MetalLB IP Address Pool Configuration
metallb_ip_pool_name: "default-pool"
metallb_ip_range: "192.168.1.200-192.168.1.250"
metallb_protocol: "layer2"

# MetalLB Speaker Configuration
metallb_speaker_enabled: true
metallb_speaker_resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "100Mi"

# MetalLB Controller Configuration
metallb_controller_resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "100Mi"

# MetalLB Installation Method
metallb_install_method: "manifest"  # Options: manifest, helm

# MetalLB Helm Chart Configuration (if using helm method)
metallb_helm_repo_url: "https://metallb.github.io/metallb"
metallb_helm_repo_name: "metallb"
metallb_helm_chart_name: "metallb"
metallb_helm_release_name: "metallb"

# MetalLB State (present/absent)
metallb_state: "present"

# MetalLB Service Configuration
metallb_service_external_traffic_policy: "Local"
metallb_service_internal_traffic_policy: "Cluster"

# MetalLB Advertisement Configuration
metallb_advertisement_name: "default-advertisement"
metallb_advertisement_aggregation_length: null
metallb_advertisement_communities: []

# MetalLB Node Selection
metallb_node_selector: {}
metallb_speaker_tolerations: []

# MetalLB Configuration Template
metallb_config_template: "metallb-config.yaml.j2"
metallb_ipaddresspool_template: "metallb-ipaddresspool.yaml.j2"
metallb_advertisement_template: "metallb-advertisement.yaml.j2"