---
- name: Remove Cilium Helm release
  kubernetes.core.helm:
    name: "{{ cilium_release_name }}"
    release_namespace: "{{ cilium_namespace }}"
    state: absent
    kubeconfig: "{{ kubeconfig_path }}"
  failed_when: false

- name: Wait for Cilium DaemonSet to be removed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: DaemonSet
    name: cilium
    namespace: "{{ cilium_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"
  register: cilium_daemonset_check
  until: cilium_daemonset_check.resources | length == 0
  retries: 20
  delay: 5
  failed_when: false

- name: Remove Cilium CRDs (cleanup)
  kubernetes.core.k8s:
    state: absent
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "{{ item }}"
    kubeconfig: "{{ kubeconfig_path }}"
  loop:
    - ciliumnetworkpolicies.cilium.io
    - ciliumendpoints.cilium.io
    - ciliumnodes.cilium.io
    - ciliumidentities.cilium.io
  failed_when: false

- name: Remove Cilium Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    state: absent
    kubeconfig: "{{ kubeconfig_path }}"
  failed_when: false

- name: Display removal status
  debug:
    msg: "✅ Cilium CNI removed successfully"