---
# Unified K3s role defaults
# Supports both server (control plane) and agent (worker) nodes

# Node role configuration (server or agent)
node_role: "{{ k3s_node_role | default('server') }}"

# K3s version and installation
k3s_version: "v1.33.1+k3s1"
k3s_channel: "stable"
k3s_state: "{{ k3s_state | default('present') }}"
k3s_install_dir: "/usr/local/bin"
k3s_install_script_url: "https://get.k3s.io"

# K3s directories
k3s_data_dir: "/var/lib/rancher/k3s"
k3s_config_dir: "/etc/rancher/k3s"
k3s_token_file: "{{ k3s_data_dir }}/server/node-token"

# Network configuration
k3s_cluster_cidr: "{{ k3s_pod_cidr | default('10.42.0.0/16') }}"
k3s_service_cidr: "{{ k3s_service_cidr | default('10.43.0.0/16') }}"
k3s_cluster_dns: "10.43.0.10"

# Common K3s arguments (applied to both server and agent)
k3s_common_args:
  - "--node-name={{ inventory_hostname }}"

# Server-specific configuration
k3s_server_args:
  - "--write-kubeconfig-mode=644"
  - "--disable=traefik"
  - "--disable=servicelb" 
  - "--disable-network-policy"
  - "--flannel-backend=none"
  - "--disable-cloud-controller"
  - "--cluster-cidr={{ k3s_cluster_cidr }}"
  - "--service-cidr={{ k3s_service_cidr }}"
  - "--cluster-dns={{ k3s_cluster_dns }}"

# Agent-specific configuration
k3s_agent_args:
  - "--node-label=node-role.kubernetes.io/worker=true"

# Control plane configuration
k3s_control_plane_host: "{{ groups[kubernetes_platform + '_control_plane'][0] | default('localhost') }}"
k3s_control_plane_ip: "{{ hostvars[k3s_control_plane_host]['ansible_host'] | default('127.0.0.1') }}"
k3s_server_url: "https://{{ k3s_control_plane_ip }}:6443"

# CNI configuration (to be handled by separate CNI roles)
k3s_cni_plugin: "{{ cni_plugin | default('cilium') }}"
k3s_disable_builtin_cni: true

# Security
k3s_selinux: false
k3s_rootless: false

# Registry configuration
k3s_registries_config_file: "{{ k3s_config_dir }}/registries.yaml"
k3s_private_registries: []

# Feature flags
k3s_enable_metrics_server: true
k3s_enable_local_storage: true