---
- name: Test kubectl connectivity before Helm operations
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    kubeconfig: "{{ kubeconfig_path }}"
    validate_certs: false
  register: kubectl_test
  failed_when: false

- name: Display kubectl test results
  debug:
    msg:
      - "kubectl connectivity test: {{ 'SUCCESS' if kubectl_test.failed == false else 'FAILED' }}"
      - "Nodes found: {{ kubectl_test.resources | length if kubectl_test.resources is defined else 'None' }}"
      - "Error: {{ kubectl_test.msg if kubectl_test.failed else 'None' }}"

- name: Add NFS CSI Helm repository
  kubernetes.core.helm_repository:
    name: csi-driver-nfs
    repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    kubeconfig: "{{ kubeconfig_path }}"
    validate_certs: false

- name: Install NFS CSI driver
  kubernetes.core.helm:
    name: csi-driver-nfs
    chart_ref: csi-driver-nfs/csi-driver-nfs
    release_namespace: kube-system
    create_namespace: false
    kubeconfig: "{{ kubeconfig_path }}"
    validate_certs: false
    values:
      driver:
        name: nfs.csi.k8s.io
      controller:
        replicas: 1

- name: Create NFS StorageClass
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    validate_certs: false
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: nfs-shared
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: nfs.csi.k8s.io
      parameters:
        server: "{{ nfs_server_ip }}"
        share: "{{ nfs_path }}"
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      mountOptions:
        - nfsvers=4.1
        - rsize=1048576
        - wsize=1048576
        - hard
        - timeo=600
        - retrans=2

- name: Create test PVC to verify NFS storage
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    validate_certs: false
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: nfs-test-pvc
        namespace: default
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
        storageClassName: nfs-shared