---
- name: Check if istioctl is already installed
  stat:
    path: "{{ istioctl_binary }}"
  register: istioctl_exists
  delegate_to: "{{ control_plane_host }}"

- name: Check istioctl version if installed
  command: "{{ istioctl_binary }} version --remote=false"
  register: istioctl_version_check
  delegate_to: "{{ control_plane_host }}"
  changed_when: false
  failed_when: false
  when: istioctl_exists.stat.exists

- name: Set istioctl installation needed fact
  set_fact:
    istioctl_install_needed: >-
      {{ not istioctl_exists.stat.exists or 
         istio_version not in (istioctl_version_check.stdout | default('')) }}

- name: Download and install istioctl
  block:
    - name: Download Istio release
      unarchive:
        src: "{{ istio_download_url }}"
        dest: "/tmp"
        remote_src: yes
        creates: "/tmp/istio-{{ istio_version }}"
      delegate_to: "{{ control_plane_host }}"

    - name: Create istio bin directory
      file:
        path: "{{ istio_install_dir }}/bin"
        state: directory
        mode: '0755'
      delegate_to: "{{ control_plane_host }}"
      become: true

    - name: Copy istioctl binary to installation directory
      copy:
        src: "/tmp/istio-{{ istio_version }}/bin/istioctl"
        dest: "{{ istioctl_binary }}"
        mode: '0755'
        remote_src: yes
      delegate_to: "{{ control_plane_host }}"
      become: true

    - name: Create istioctl symlink in PATH
      file:
        src: "{{ istioctl_binary }}"
        dest: "/usr/local/bin/istioctl"
        state: link
      delegate_to: "{{ control_plane_host }}"
      become: true

    - name: Clean up temporary files
      file:
        path: "/tmp/istio-{{ istio_version }}"
        state: absent
      delegate_to: "{{ control_plane_host }}"

  when: istioctl_install_needed

- name: Verify istioctl installation
  command: "{{ istioctl_binary }} version --remote=false"
  register: istioctl_verify
  delegate_to: "{{ control_plane_host }}"
  changed_when: false

- name: Display istioctl version
  debug:
    msg: "istioctl version: {{ istioctl_verify.stdout }}"