---
- name: Include platform-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [always]

- name: Validate prerequisites
  include_tasks: validate.yml
  tags: [validation, prerequisites]

- name: Install K3s control plane
  include_tasks: install.yml
  when: k3s_state == "present"
  tags: [install, k3s, control_plane]

- name: Configure K3s control plane
  include_tasks: configure.yml
  when: k3s_state == "present"
  tags: [configure, k3s, control_plane]

- name: Remove K3s control plane
  include_tasks: uninstall.yml
  when: k3s_state == "absent"
  tags: [uninstall, k3s, control_plane]

- name: Install Calico CNI
  include_tasks: calico.yml
  when: k3s_state == "present" and calico_enabled | default(true)
  tags: [calico, cni, networking]

- name: Verify installation
  include_tasks: verify.yml
  when: k3s_state == "present"
  tags: [verify, k3s, control_plane]
