---
# Secret management configuration
secrets_base_path: "{{ playbook_dir }}/../manifests/sealed-secrets"
secrets_retry_count: 3
secrets_retry_delay: 10

# Secret mappings
minio_secrets:
  mlflow:
    file: mlflow-s3-secret.yaml
    namespace: mlflow
    required_for: [mlflow]
  
  argo:
    file: minio-credentials-wf.yaml
    namespace: argowf
    required_for: [workflows, argo]
  
  kubeflow:
    file: minio-secret-kubeflow.yaml
    namespace: kubeflow
    required_for: [kubeflow]