---
# MetalLB Variables

# MetalLB Component Labels
metallb_labels:
  app: metallb
  version: "{{ metallb_version }}"
  component: load-balancer

# MetalLB Manifest URL
metallb_manifest_url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"

# MetalLB Required Kubernetes Resources
metallb_required_resources:
  - apiVersion: v1
    kind: Namespace
    name: "{{ metallb_namespace }}"
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: metallb-system:controller
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: metallb-system:speaker
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: metallb-system:controller
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: metallb-system:speaker

# MetalLB Configuration CRDs
metallb_crds:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ipaddresspools.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: l2advertisements.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bgpadvertisements.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: communities.metallb.io

# MetalLB Service Discovery
metallb_service_discovery:
  controller:
    name: controller
    namespace: "{{ metallb_namespace }}"
    port: 7472
    metrics_port: 7472
  speaker:
    name: speaker
    namespace: "{{ metallb_namespace }}"
    port: 7946
    metrics_port: 7472

# MetalLB Network Configuration
metallb_network_config:
  strictARP: true
  nodePortAddresses: []
  ipv4_autodetection_method: "interface=eth0"
  ipv6_autodetection_method: "interface=eth0"