---
- name: Move static pod manifests (prevents restart)
  shell: |
    mkdir -p /root/k8s-manifests-backup
    mv /etc/kubernetes/manifests/* /root/k8s-manifests-backup/ 2>/dev/null || true
  become: true
  ignore_errors: yes

- name: Stop kubelet (stops managing static pods)
  systemd:
    name: kubelet
    state: stopped
    enabled: no
  become: true
  ignore_errors: yes

- name: Stop container runtime (kills static pod containers and zombie processes)
  systemd:
    name: containerd
    state: stopped
  become: true
  ignore_errors: yes

- name: Wait for all containers to be killed
  wait_for:
    timeout: 5
  delegate_to: localhost

- name: Reset kubeadm cluster
  command: kubeadm reset --force
  become: true
  ignore_errors: yes

- name: Remove Kubernetes configuration
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - "{{ ansible_env.HOME }}/.kube"
    - /var/lib/etcd
    - /var/lib/kubelet
  become: true

- name: Unhold Kubernetes packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true
  ignore_errors: yes

- name: Remove Kubernetes packages
  package:
    name: "{{ kubernetes_packages }}"
    state: absent
  become: true

- name: Clean up iptables rules
  command: "{{ item }}"
  loop:
    - iptables -F
    - iptables -t nat -F
    - iptables -t mangle -F
    - iptables -X
  become: true
  ignore_errors: yes